
services:
  vinyl-print:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: vinyl-print
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=vinyl-print
      - tsdproxy.port=3000
