
services:
  vinyl-print:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: vinyl-print
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=vinyl-print
      - tsdproxy.port=80
    networks:
      - default
      - tsdproxy

networks:
  tsdproxy:
    external: true
    name: tsdproxy_default
